// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------ //
// ov7670 //
// ------ //

#define ov7670_wrap_target 0
#define ov7670_wrap 11
#define ov7670_pio_version 0

static const uint16_t ov7670_program_instructions[] = {
            //     .wrap_target
    0xe033, //  0: set    x, 19
    0xe047, //  1: set    y, 7
    0x20aa, //  2: wait   1 pin, 10
    0x20a8, //  3: wait   1 pin, 8
    0x4908, //  4: in     pins, 8                [9]
    0x4008, //  5: in     pins, 8
    0x8020, //  6: push   block
    0x2028, //  7: wait   0 pin, 8
    0x0043, //  8: jmp    x--, 3
    0xe033, //  9: set    x, 19
    0x0083, // 10: jmp    y--, 3
    0x202a, // 11: wait   0 pin, 10
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program ov7670_program = {
    .instructions = ov7670_program_instructions,
    .length = 12,
    .origin = -1,
    .pio_version = ov7670_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config ov7670_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + ov7670_wrap_target, offset + ov7670_wrap);
    return c;
}
#endif

